USB_VID = 0x303A
USB_PID = 0x700F

USB_PRODUCT = "TulipCC R11"
USB_MANUFACTURER = "MakerFabs"

IDF_TARGET = esp32s3
# ESP32-S3-WROOM-2-N32R8V
# 32M Flash, 8M PSRAM

CIRCUITPY_ESP_FLASH_MODE = opi
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 32MB

CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m

CIRCUITPY_ESPCAMERA = 0
CIRCUITPY_DOTCLOCKFRAMEBUFFER = 1
#CIRCUITPY_DISPLAYIO = 1
#CIRCUITPY_WIFI = 1
#CIRCUITPY_BUILD_EXTENSIONS = bin,uf2
#UF2_BOOTLOADER = 1
